version: "3.8"
services:
  busybox:
    image: busybox:1.33.1
    command: /tmp/output-log.sh
    volumes:
      - "./busybox/output-log.sh:/tmp/output-log.sh:ro"
      - "log:/log"
  fluent-bit:
    image: fluent/fluent-bit:1.8.6
    volumes:
      - "./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro"
      - "log:/log"
  influxdb:
    image: influxdb:2.0.8
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: secretsecret
      DOCKER_INFLUXDB_INIT_ORG: default
      DOCKER_INFLUXDB_INIT_BUCKET: default
      DOCKER_INFLUXDB_INIT_RETENTION: 1d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: a978706d0b31982012155105339b783b
    ports:
      - "8086:8086"
#  chronograf:
#    image: chronograf:1.9.0
#    command: chronograf --influxdb-url=http://influxdb:8086
#    ports:
#      - "8888:8888"
volumes:
  log:

